### ISSUE TITLE
Variant's are not capable of having seperate rarities

### ISSUE THREAD

**Issue by Vek17** [BlueWinds/RarityTiedSpawner#1]
With the current implementation using ``unitDef.FriendlyName`` as the key in the caching layer the first loaded variant's rarity will be applied to all variants. To allow all units to calculate with the rarity defined in their def the use of  ``unitDef.UnitDefID`` is appropriate.

**Comment by BlueWinds** [comment]
Looks like you're right; thanks for the report and the PR! Closing this because the PR is merged.
